wagtail/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from wagtail import views
from wagtail.coreutils import WAGTAIL_APPEND_SLASH

if WAGTAIL_APPEND_SLASH:
    # If WAGTAIL_APPEND_SLASH is True (the default value), we match a
    # (possibly empty) list of path segments ending in slashes.
    # CommonMiddleware will redirect requests without a trailing slash to
    # a URL with a trailing slash
    serve_pattern = r"^((?:[\w\-]+/)*)$"
else:
    # If WAGTAIL_APPEND_SLASH is False, allow Wagtail to serve pages on URLs
    # with and without trailing slashes
    serve_pattern = r"^([\w\-/]*)$"


WAGTAIL_FRONTEND_LOGIN_TEMPLATE = getattr(
    settings, "WAGTAIL_FRONTEND_LOGIN_TEMPLATE", "wagtailcore/login.html"
)


urlpatterns = [
    path(
        "_util/authenticate_with_password/<int:page_view_restriction_id>/<int:page_id>/",
        views.authenticate_with_password,
        name="wagtailcore_authenticate_with_password",
    ),
    path(
        "_util/login/",
        auth_views.LoginView.as_view(template_name=WAGTAIL_FRONTEND_LOGIN_TEMPLATE),
        name="wagtailcore_login",
    ),
    # Front-end page views are handled through Wagtail's core.views.serve
    # mechanism
    re_path(serve_pattern, views.serve, name="wagtail_serve"),
]

wagtail/admin/forms/search.py
from django import forms
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy


class SearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        placeholder = kwargs.pop("placeholder", _("Search"))
        super().__init__(*args, **kwargs)
        self.fields["q"].widget.attrs = {"placeholder": placeholder}

    q = forms.CharField(label=gettext_lazy("Search term"), widget=forms.TextInput())

wagtail/contrib/modeladmin/forms.py
from django import forms
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _

from wagtail.models import Page


class PageChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        bits = []
        for ancestor in (
            obj.get_ancestors(inclusive=True).exclude(depth=1).specific(defer=True)
        ):
            bits.append(ancestor.get_admin_display_title())
        return mark_safe('<span class="icon icon-arrow-right"></span>'.join(bits))


class ParentChooserForm(forms.Form):
    parent_page = PageChoiceField(
        label=_("Parent page"),
        required=True,
        empty_label=None,
        queryset=Page.objects.none(),
        widget=forms.RadioSelect(),
    )

    def __init__(self, valid_parents_qs, *args, **kwargs):
        self.valid_parents_qs = valid_parents_qs
        super().__init__(*args, **kwargs)
        self.fields["parent_page"].queryset = self.valid_parents_qs

wagtail/search/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class QueryForm(forms.Form):
    query_string = forms.CharField(
        label=_("Search term(s)/phrase"),
        help_text=_(
            "Enter the full search string to match. An "
            "exact match is required for your Promoted Results to be "
            "displayed, wildcards are NOT allowed."
        ),
        required=True,
    )

wagtail/contrib/modeladmin/views.py
import warnings
from collections import OrderedDict

from django import forms
from django.conf import settings
from django.contrib.admin import FieldListFilter
from django.contrib.admin.options import IncorrectLookupParameters
from django.contrib.admin.utils import (
    get_fields_from_path,
    label_for_field,
    lookup_field,
    prepare_lookup_value,
    quote,
    unquote,
)
from django.contrib.auth.decorators import login_required
from django.core.exceptions import (
    FieldDoesNotExist,
    ImproperlyConfigured,
    ObjectDoesNotExist,
    PermissionDenied,
    SuspiciousOperation,
)
from django.core.paginator import InvalidPage, Paginator
from django.db import models, transaction
from django.db.models.fields.related import ManyToManyField, OneToOneRel
from django.shortcuts import get_object_or_404, redirect
from django.template.defaultfilters import filesizeformat
from django.utils.decorators import method_decorator
from django.utils.encoding import force_str
from django.utils.functional import cached_property
from django.utils.http import urlencode
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.views.generic.list import MultipleObjectMixin

from wagtail.admin import messages
from wagtail.admin.ui.tables import Column, DateColumn, Table, UserColumn
from wagtail.admin.views.generic.base import WagtailAdminTemplateMixin
from wagtail.admin.views.mixins import SpreadsheetExportMixin
from wagtail.log_actions import log
from wagtail.log_actions import registry as log_registry
from wagtail.models import Locale, TranslatableMixin
from wagtail.utils.deprecation import RemovedInWagtail50Warning

from .forms import ParentChooserForm

try:
    from django.contrib.admin.utils import lookup_spawns_duplicates
except ImportError:
    # fallback for Django <4.0
    from django.contrib.admin.utils import (
        lookup_needs_distinct as lookup_spawns_duplicates,
    )


QUERY_TERMS = {
    "contains",
    "day",
    "endswith",
    "exact",
    "gt",
    "gte",
    "hour",
    "icontains",
    "iendswith",
    "iexact",
    "in",
    "iregex",
    "isnull",
    "istartswith",
    "lt",
    "lte",
    "minute",
    "month",
    "range",
    "regex",
    "search",
    "second",
    "startswith",
    "week_day",
    "year",
}


class WMABaseView(TemplateView):
    """
    Groups together common functionality for all app views.
    """

    model_admin = None
    meta_title = ""
    page_title = ""
    page_subtitle = ""

    def __init__(self, model_admin):
        self.model_admin = model_admin
        self.model = model_admin.model
        self.opts = self.model._meta
        self.app_label = force_str(self.opts.app_label)
        self.model_name = force_str(self.opts.model_name)
        self.verbose_name = force_str(self.opts.verbose_name)
        self.verbose_name_plural = force_str(self.opts.verbose_name_plural)
        self.pk_attname = self.opts.pk.attname
        self.is_pagemodel = model_admin.is_pagemodel
        self.permission_helper = model_admin.permission_helper
        self.url_helper = model_admin.url_helper

    def check_action_permitted(self, user):
        return True

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not self.check_action_permitted(request.user):
            raise PermissionDenied
        button_helper_class = self.model_admin.get_button_helper_class()
        self.button_helper = button_helper_class(self, request)
        return super().dispatch(request, *args, **kwargs)

    @cached_property
    def menu_icon(self):
        return self.model_admin.get_menu_icon()

    @cached_property
    def header_icon(self):
        return self.menu_icon

    def get_page_title(self):
        return self.page_title or capfirst(self.opts.verbose_name_plural)

    def get_meta_title(self):
        return self.meta_title or self.get_page_title()

    @cached_property
    def index_url(self):
        return self.url_helper.index_url

    @cached_property
    def create_url(self):
        return self.url_helper.create_url

    def get_base_queryset(self, request=None):
        return self.model_admin.get_queryset(request or self.request)

    def get_context_data(self, **kwargs):
        context = {
            "view": self,
            "model_admin": self.model_admin,
        }
        context.update(kwargs)
        return super().get_context_data(**context)


class ModelFormView(WMABaseView, FormView):
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.edit_handler = self.get_edit_handler()

    def get_form(self):
        form = super().get_form()
        return form

    def get_edit_handler(self):
        try:
            edit_handler = self.model_admin.get_edit_handler()
        except TypeError:
            edit_handler = self.model_admin.get_edit_handler(
                instance=None, request=None
            )
            warnings.warn(
                "%s.get_edit_handler should not accept instance or request arguments"
                % type(self.model_admin).__name__,
                category=RemovedInWagtail50Warning,
            )

        return edit_handler.bind_to_model(self.model_admin.model)

    def get_form_class(self):
        return self.edit_handler.get_form_class()

    def get_success_url(self):
        return self.index_url

    def get_instance(self):
        return getattr(self, "instance", None) or self.model()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"instance": self.get_instance(), "for_user": self.request.user})
        return kwargs

    @property
    def media(self):
        return forms.Media(
            css={"all": self.model_admin.get_form_view_extra_css()},
            js=self.model_admin.get_form_view_extra_js(),
        )

    def get_context_data(self, form=None, **kwargs):
        if form is None:
            form = self.get_form()

        bound_panel = self.edit_handler.get_bound_panel(
            form=form, instance=form.instance, request=self.request
        )

        prepopulated_fields = self.get_prepopulated_fields(form)
        context = {
            "is_multipart": form.is_multipart(),
            "edit_handler": bound_panel,
            "form": form,
            "prepopulated_fields": prepopulated_fields,
            "media": self.media + bound_panel.media + form.media,
        }
        context.update(kwargs)
        return super().get_context_data(**context)

    def get_prepopulated_fields(self, form):
        fields = []
        for field_name, dependencies in self.model_admin.get_prepopulated_fields(
            self.request
        ).items():
            missing_dependencies = [
                f"'{f}'" for f in dependencies if f not in form.fields
            ]
            if len(missing_dependencies) != 0:
                missing_deps_string = ", ".join(missing_dependencies)
                dependency_string = (
                    "dependencies" if len(missing_dependencies) > 1 else "dependency"
                )
                warnings.warn(
                    f"Missing {dependency_string} {missing_deps_string} for prepopulated_field '{field_name}''.",
                    category=RuntimeWarning,
                )
            elif field_name in form.fields:
                fields.append(
                    {
                        "field": form[field_name],
                        "dependencies": [form[f] for f in dependencies],
                    }
                )
        return fields

    def get_success_message(self, instance):
        return _("%(model_name)s '%(instance)s' created.") % {
            "model_name": capfirst(self.opts.verbose_name),
            "instance": instance,
        }

    def get_success_message_buttons(self, instance):
        button_url = self.url_helper.get_action_url("edit", quote(instance.pk))
        return [messages.button(button_url, _("Edit"))]

    def get_error_message(self):
        model_name = self.verbose_name
        return _("The %s could not be created due to errors.") % model_name

    def form_valid(self, form):
        self.instance = form.save()
        messages.success(
            self.request,
            self.get_success_message(self.instance),
            buttons=self.get_success_message_buttons(self.instance),
        )
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        messages.validation_error(self.request, self.get_error_message(), form)
        return self.render_to_response(self.get_context_data(form=form))


class InstanceSpecificView(WMABaseView):

    instance_pk = None
    pk_quoted = None
    instance = None
    locale = None

    def __init__(self, model_admin, instance_pk):
        super().__init__(model_admin)
        self.instance_pk = unquote(instance_pk)
        self.pk_quoted = quote(self.instance_pk)
        filter_kwargs = {}
        filter_kwargs[self.pk_attname] = self.instance_pk
        object_qs = model_admin.model._default_manager.get_queryset().filter(
            **filter_kwargs
        )
        self.instance = get_object_or_404(object_qs)

        if getattr(settings, "WAGTAIL_I18N_ENABLED", False) and issubclass(
            model_admin.model, TranslatableMixin
        ):
            self.locale = self.instance.locale

    def get_page_subtitle(self):
        return self.instance

    @cached_property
    def edit_url(self):
        return self.url_helper.get_action_url("edit", self.pk_quoted)

    @cached_property
    def delete_url(self):
        return self.url_helper.get_action_url("delete", self.pk_quoted)

    def get_context_data(self, **kwargs):

wagtail/project_template/search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(
        request,
        "search/search.html",
        {
            "search_query": search_query,
            "search_results": search_results,
        },
    )

wagtail/search/views/queries.py
from django.core.paginator import Paginator
from django.template.response import TemplateResponse

from wagtail.admin.forms.search import SearchForm
from wagtail.admin.modal_workflow import render_modal_workflow
from wagtail.search import models
from wagtail.search.utils import normalise_query_string


def chooser(request, get_results=False):
    # Get most popular queries
    queries = models.Query.get_most_popular()

    # If searching, filter results by query string
    query_string = None
    if "q" in request.GET:
        searchform = SearchForm(request.GET)
        if searchform.is_valid():
            query_string = searchform.cleaned_data["q"]
            queries = queries.filter(
                query_string__icontains=normalise_query_string(query_string)
            )
    else:
        searchform = SearchForm()

    paginator = Paginator(queries, per_page=10)
    queries = paginator.get_page(request.GET.get("p"))

    # Render
    if get_results:
        return TemplateResponse(
            request,
            "wagtailsearch/queries/chooser/results.html",
            {
                "queries": queries,
            },
        )
    else:
        return render_modal_workflow(
            request,
            "wagtailsearch/queries/chooser/chooser.html",
            None,
            {
                "queries": queries,
                "searchform": searchform,
            },
            json_data={"step": "chooser"},
        )


def chooserresults(request):
    return chooser(request, get_results=True)

wagtail/contrib/modeladmin/templates/modeladmin/includes/breadcrumb.html
{% load i18n wagtailadmin_tags %}
<ul class="breadcrumb">
    {% trans 'Home' as home %}
    <li class="breadcrumb-item home"><a href="{% url 'wagtailadmin_home' %}" class="breadcrumb-link">{% icon name="home" class_name="home_icon" title=home %}{% icon name="arrow-right" class_name="arrow_right_icon" %}</a></li>
    <li class="breadcrumb-item"><a href="{{ view.index_url }}" class="breadcrumb-link">{{ view.verbose_name_plural|capfirst }}</a></li>
</ul>

wagtail/contrib/modeladmin/templates/modeladmin/includes/button.html
<a{% if button.url %} href="{{ button.url }}"{% endif %} class="{{ button.classname }}" title="{{ button.title }}"{% if button.target %} target="{{ button.target }}"{% endif %}{% if button.rel %} rel="{{ button.rel }}"{% endif %}>{{ button.label }}</a>

wagtail/contrib/modeladmin/templates/modeladmin/includes/filter.html
{% load i18n %}
{% blocktrans trimmed with filter_title=title %} By {{ filter_title }} {% endblocktrans %}
<ul>
    {% for choice in choices %}
        <li{% if choice.selected %} class="selected"{% endif %}>
            <a href="{{ choice.query_string|iriencode }}">{{ choice.display }}</a></li>
    {% endfor %}
</ul>

wagtail/contrib/modeladmin/templates/modeladmin/includes/header_with_breadcrumb.html
{% extends "wagtailadmin/shared/header_with_locale_selector.html" %}

{% block breadcrumb %}
    {% include "modeladmin/includes/breadcrumb.html" %}
{% endblock %}

wagtail/contrib/modeladmin/templates/modeladmin/includes/header_with_history.html
{% extends "wagtailadmin/shared/header_with_locale_selector.html" %}
{% load wagtailadmin_tags i18n %}

{% block extra_rows %}
    <div class="row last-updated">
        {% if latest_log_entry %}
            <ul>
                <li>
                    <span class="avatar small" data-wagtail-tooltip="{{ latest_log_entry.user_display_name }}"><img src="{% avatar_url latest_log_entry.user size=25 %}" alt="" /></span>
                    {% trans "Last updated" %}
                    {% include "wagtailadmin/shared/last_updated.html" with last_updated=latest_log_entry.timestamp time_prefix="at" %}
                </li>
                {% if history_url %}
                    <li><a href="{{ history_url }}">{% icon "history" class_name="default" %} {% trans "History" %}</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

wagtail/contrib/modeladmin/templates/modeladmin/includes/result_count.html
{% load i18n %}
{% block result_count %}
    <span class="result-count">{% blocktrans trimmed %}{{ result_count }} out of {{ all_count }}{% endblocktrans %}</span>
{% endblock %}

wagtail/contrib/modeladmin/templates/modeladmin/includes/result_list.html
{% load i18n modeladmin_tags %}
{% if results %}
    <table class="listing full-width">
        <thead>
            <tr>
                {% for header in result_headers %}
                    <th scope="col" {{ header.class_attrib }}>
                        {% if header.sortable %}<a href="{{ header.url_primary }}" class="icon {% if header.ascending %}icon-arrow-up-after{% else %}icon-arrow-down-after{% endif %}">{% endif %}
                        {{ header.text|capfirst }}
                        {% if header.sortable %}</a>{% endif %}
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for result in results %}
                {% result_row_display forloop.counter0 %}
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="nice-padding no-search-results">
        <p>{% blocktrans trimmed with view.verbose_name_plural as name %}Sorry, there are no {{ name }} matching your search parameters.{% endblocktrans %}</p>
    </div>
{% endif %}

wagtail/contrib/modeladmin/templates/modeladmin/includes/result_row.html
{% load modeladmin_tags %}
<tr{{ row_attrs }}>
    {% for item in result %}
        {% result_row_value_display forloop.counter0 %}
    {% endfor %}
</tr>

wagtail/contrib/modeladmin/templates/modeladmin/includes/result_row_value.html
{% load i18n modeladmin_tags %}
{{ item }}{% if add_action_buttons %}
    {% if action_buttons %}
        <ul class="actions">
            {% for button in action_buttons %}
                <li>{% include 'modeladmin/includes/button.html' %}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {{ closing_tag }}
{% endif %}

wagtail/contrib/modeladmin/templates/modeladmin/includes/search_form.html
{% load i18n wagtailadmin_tags %}
{% if show_search %}
    <form id="changelist-search" class="col search-form" action="{{ view.index_url }}" method="get">
        <ul class="fields">
            <li class="required">
                <div class="field char_field text_input field-small iconfield">
                    <label for="id_q" class="visuallyhidden">{% trans 'Search for' %}</label>
                    <div class="field-content">
                        <div class="input">
                            {% icon name="search" %}
                            <input id="id_q" name="{{ search_var }}" value="{{ view.query }}" placeholder="{% blocktrans trimmed with view.verbose_name_plural|lower as name %}Search {{ name }}{% endblocktrans %}" type="text">
                            <span></span>
                        </div>
                    </div>
                </div>
            </li>
            <li class="submit visuallyhidden"><input type="submit" value="Search" class="button"></li>
        </ul>
    </form>
    <script type="text/javascript">document.getElementById("id_q").focus();</script>
{% endif %}